---
- name: Include new bastion ips
  include_vars: "{{inventory_dir}}/group_vars/new-bastion-ips.yml"

- name: Get rule number for bastion
  shell: "ufw status numbered | grep {{ change_bastion_ips['old'] }} | awk -F '[][]' '{print $2}'"
  register: ufw_rule_number
  become: true

- name: Replace allow old bastion IP with new one
  shell: "ufw delete allow from {{ change_bastion_ips['old'] }} to any port 22 proto tcp && ufw insert {{ ufw_rule_number.stdout | regex_replace(' ', '') }} allow from {{ change_bastion_ips['new'] }} to any port 22 proto tcp comment '{{ change_bastion_ips['comment'] }}'"
  become: true
  when: ufw_rule_number.stdout | regex_replace(' ', '') is regex('^[0-9]+$')
