# Variables that apply to all production hosts.

prom_url: https://mimir.example.com/api/v1/push
loki_url: https://loki.example.com/loki/api/v1/push
prom_cf_id: cloudflare-zerotrust-token.access
prom_cf_secret: cloudflare-zerotrust-secret

extra_send_metrics_logs:
  sending_to_1:
    servers_hostnames: ["all"]
    metrics:
      url: https://METRICS_URL_1111
      username: METRICS_USERNAME_1111
      password: METRICS_PASSWORD_1111
    logs:
      url: https://LOGS_URL_1111
      username: LOGS_USERNAME_1111
      password: LOGS_PASSWORD_1111
      operator: LOGS_OPERATOR_1111
  sending_to_2:
    servers_hostnames: ["server1", "server2"]
    metrics:
      url: https://METRICS_URL_2222
      username: METRICS_USERNAME_2222
      password: METRICS_PASSWORD_2222
    logs:
      url: https://LOGS_URL_2222
      username: LOGS_USERNAME_2222
      password: LOGS_PASSWORD_2222
      operator: LOGS_OPERATOR_2222
  sending_to_3:
    servers_hostnames: ["all"]
    logs:
      url: https://LOGS_URL_3333
      username: LOGS_USERNAME_3333
      password: LOGS_PASSWORD_3333
      operator: LOGS_OPERATOR_3333

# Crowdstrike
falcon_url_ubuntu: "https://fqdn-for/falcon-sensor-ubuntu-x86_64.deb"
falcon_url_debian: "https://fqdn-for/falcon-sensor-debian-amd64.deb"
falcon_cid: "my-cid"

# Unattended Upgrades
upgrades_UU_CONF: /etc/apt/apt.conf.d/50unattended-upgrades
upgrades_UU_START: /etc/apt/apt.conf.d/20auto-upgrades
upgrades_EMAIL_TO: user@example.com
upgrades_EMAIL: user@example.com
upgrades_EPW: password
upgrades_MAILSRV: smtp.gmail.com:587
upgrades_REBOOT_AT: -02:00

infra_bastion: 192.168.1.10
infra_bastion_backup: 192.168.1.11
infra_bastion_hostname: bastion.example.com
infra_bastion_backup_hostname: bastion-backup.example.com
bastion_username: jdoe
ssh_keys_path: ~/.ssh
ansible_ssh_extra_args: "-o StrictHostKeyChecking=accept-new -o ProxyCommand=\"bash -c 'cloudflared access ssh-gen --hostname {{ infra_bastion_hostname }}; ssh -W %h:%p {{ bastion_username }}@cfpipe-{{ infra_bastion_hostname }}'\""
ansible_ssh_private_key_file: "{{ ssh_keys_path }}/mykey.pem"

ufw:
  allow:
    - cidr: 192.168.1.100/32
      port: 443
      protocol: tcp
      description: Allow port 443 access from known server
